import type { Metadata } from "next";
import ContentPage from "../../../components/ContentPage";

export const metadata: Metadata = { title: "Hard Bounces, Soft Bounces, and Email Blocks — Clearlist", description: "Understand bounce categories, SMTP responses, suppression, and what to do after an email campaign fails.", alternates: { canonical: "/guides/email-bounces" } };

export default function EmailBouncesGuide() {
  return (
    <ContentPage kicker="Operations guide" title="Not every failed email means the same thing" intro="A useful bounce process separates permanent address failures from temporary delivery pressure and policy blocks.">
      <section><h2>What a bounce tells you</h2><p>A bounce is a delivery-status response generated after a sending system attempts to hand off a message. The response usually contains an SMTP code, an enhanced status code, and human-readable text. Treat all three as evidence. The friendly description in a dashboard can hide details that matter.</p><p>Verification happens before a campaign and can reduce predictable failures. Bounce handling happens after a real delivery attempt and is the authoritative source for what occurred during that send.</p></section>
      <section><h2>Hard bounces</h2><p>A hard bounce is a permanent failure. Common causes include a nonexistent mailbox, a domain that cannot receive mail, or a recipient address that the organization permanently disabled. Suppress the exact address immediately. Repeatedly sending to the same hard bounce wastes capacity and signals poor list maintenance.</p><p>Do not automatically suppress an entire domain because one address failed. A company may remove one employee while every other mailbox remains active.</p></section>
      <section><h2>Soft bounces and deferrals</h2><p>Temporary failures include a full mailbox, a receiving server outage, rate limiting, greylisting, or a message that is temporarily too large. A controlled retry may succeed. Your sending provider should use an appropriate retry schedule; manually resending the same campaign in quick succession can make the problem worse.</p><p>When many recipients at one provider defer at the same time, investigate reputation, volume, and authentication before blaming each address.</p></section>
      <section><h2>Policy blocks</h2><p>A block can occur even when the mailbox exists. Providers may reject mail because of domain reputation, IP reputation, missing authentication, suspicious links, complaint history, message content, or recipient-specific rules. A policy block is a sender problem until evidence shows otherwise. Removing the recipient alone does not fix the underlying cause.</p></section>
      <section><h2>A practical response workflow</h2><ol><li>Capture the raw bounce code and text from the sending provider.</li><li>Classify it as permanent recipient failure, temporary failure, or sender/policy block.</li><li>Suppress permanent failures before the next campaign.</li><li>Allow the sending platform to retry legitimate temporary failures within its normal window.</li><li>Pause or reduce volume when provider-wide deferrals or blocks increase.</li><li>Review SPF, DKIM, DMARC alignment, link domains, complaints, and recent list sources.</li></ol></section>
      <section><h2>Metrics to review together</h2><p>Bounce rate alone is incomplete. Review hard bounces, temporary deferrals, spam complaints, unsubscribes, provider distribution, and reply quality by campaign and sending identity. A low bounce campaign can still be harmful when recipients did not expect it and complaints rise.</p></section>
    </ContentPage>
  );
}
